version: "3.8"
services:
  snakegame:
    container_name: web-march
    image: app-dev-web-march
    tty: true
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
    build:
      context: ./
      # target: developments
    volumes:
      - ./src:/WebMarch/src
    ports:
      - 3000:3000